apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4d-prereqs
  namespace: openshift-gitops
spec:
  destination:
    namespace: cp4d-install
    server: https://kubernetes.default.svc
  source:
    path: cp4d-prereqs/5.2.0
    repoURL: https://github.com/schabrolles/cp4d-argo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true