apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4d-prereqs
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: cert-manager
        namespace: cert-manager-operator
      - name: nfd-operator
        namespace: openshift-nfd
  template:
    metadata:
      name: '{{.name}}'
    spec:
      source:
        repoURL: https://github.com/schabrolles/cp4d-argo.git
        targetRevision: HEAD
        path: '{{.name}}'
      destination:
        namespace: '{{.namespace}}'
        server: https://kubernetes.default.svc
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true