apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-inferenceservice-config
  namespace: redhat-ods-applications
spec:
  serviceAccountRef:
    name: redhat-ods-operator-controller-manager
  patches:
    patch-inferenceservice-config:
      targetObjectRef:
        apiVersion: v1
        kind: ConfigMap
        name: inferenceservice-config
        namespace: redhat-ods-applications
      patchType: application/strategic-merge-patch+json
      patchTemplate: |
        metadata:
          annotations:
            opendatahub.io/managed: "false"
