apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-inferenceservice-config
  namespace: openshift-gitops
spec:
  serviceAccountRef:
    name: openshift-gitops-argocd-application-controller
  patches:
    patch-inferenceservice-config:
      targetObjectRef:
        apiVersion: v1
        kind: ConfigMap
        name: inferenceservice-config
        namespace: redhat-ods-applications
      patchTemplate: |
        metadata:
          annotations:
            opendatahub.io/managed: "false"
