apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: patch-inferenceservice-config
  namespace: patch-operator
spec:
  serviceAccountRef:
    name: controller-manager
  patches:
    patch-inferenceservice-config:
      targetObjectRef:
        apiVersion: v1
        kind: ConfigMap
        name: inferenceservice-config
        namespace: redhat-ods-applications
      patchType: application/strategic-merge-patch+json
      patchTemplate: |
        metadata:
          annotations:
            opendatahub.io/managed: "false"
        data:
          ingress: |-
            {
              "disableIngressCreation": true,
              "disableIstioVirtualHost": false,
              "domainTemplate": "example.com",
              "ingressClassName": "istio",
              "ingressDomain": "example.com",
              "ingressGateway": "knative-serving/knative-ingress-gateway",
              "ingressService": "istio-ingressgateway.istio-system.svc.cluster.local",
              "knativeLocalGatewayService": "knative-local-gateway.istio-system.svc.cluster.local",
              "localGateway": "istio-system/kserve-local-gateway",
              "localGatewayService": "kserve-local-gateway.istio-system.svc.cluster.local",
              "urlScheme": "https"
            }
