apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpd-install-pipeline
spec:
  project: default
  source:
    repoURL: https://schabrolles.github.io/cpd-install-pipeline
    targetRevision: 2.2.0
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: default_cpd_install
          value: watsonx
    chart: cpd-install-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: cpd-install
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
