apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfd-operator
  namespace: openshift-gitops
spec:
  ignoreDifferences:
  - group: '*'
    kind: '*'
    managedFieldsManagers:
    - kube-controller-manager
    - nfd-operator 
  project: default
  source:
    repoURL: 'https://github.com/schabrolles/cp4d-argo.git'
    targetRevision: main
    path: 'nfd-operator'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-nfd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true