apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai
  namespace: openshift-gitops
spec:
  ignoreDifferences:
  - group: '*'
    kind: '*'
    managedFieldsManagers:
    - kube-controller-manager
    - redhat-ods-operator
  project: default
  source:
    repoURL: 'https://github.com/schabrolles/cp4d-argo.git'
    targetRevision: main
    path: 'openshiftAI/2.19'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redhat-ods-operator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

