apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpd-install-pipeline
spec:
  project: default
  source:
    helm:
      parameters:
        - name: default_cpd_install
          value: watsonx
        - name: version
          value: 5.2.0